DEPRECATION WARNING: warning: white_list_sanitizer isdeprecated, please use safe_list_sanitizer instead. (called from block in <module:ContentHelper> at /Users/victormrecabarren/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/actiontext-6.0.0.rc2/app/helpers/action_text/content_helper.rb:7)
Started GET "/" for ::1 at 2019-08-07 20:41:25 -0400
  
PG::ConnectionBad (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
):
  
pg (1.1.4) lib/pg.rb:56:in `initialize'
pg (1.1.4) lib/pg.rb:56:in `new'
pg (1.1.4) lib/pg.rb:56:in `connect'
activerecord (6.0.0.rc2) lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
activerecord (6.0.0.rc2) lib/active_record/connection_adapters/abstract/connection_pool.rb:879:in `new_connection'
activerecord (6.0.0.rc2) lib/active_record/connection_adapters/abstract/connection_pool.rb:923:in `checkout_new_connection'
activerecord (6.0.0.rc2) lib/active_record/connection_adapters/abstract/connection_pool.rb:902:in `try_to_checkout_new_connection'
activerecord (6.0.0.rc2) lib/active_record/connection_adapters/abstract/connection_pool.rb:863:in `acquire_connection'
activerecord (6.0.0.rc2) lib/active_record/connection_adapters/abstract/connection_pool.rb:587:in `checkout'
activerecord (6.0.0.rc2) lib/active_record/connection_adapters/abstract/connection_pool.rb:431:in `connection'
activerecord (6.0.0.rc2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1106:in `retrieve_connection'
activerecord (6.0.0.rc2) lib/active_record/connection_handling.rb:231:in `retrieve_connection'
activerecord (6.0.0.rc2) lib/active_record/connection_handling.rb:199:in `connection'
activerecord (6.0.0.rc2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.0.rc2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.0.rc2) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.0.rc2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.0.rc2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.0.rc2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.0.rc2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.0.rc2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.0.rc2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
railties (6.0.0.rc2) lib/rails/engine.rb:526:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/favicon.ico" for ::1 at 2019-08-07 20:41:26 -0400
  
PG::ConnectionBad (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
):
  
pg (1.1.4) lib/pg.rb:56:in `initialize'
pg (1.1.4) lib/pg.rb:56:in `new'
pg (1.1.4) lib/pg.rb:56:in `connect'
activerecord (6.0.0.rc2) lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
activerecord (6.0.0.rc2) lib/active_record/connection_adapters/abstract/connection_pool.rb:879:in `new_connection'
activerecord (6.0.0.rc2) lib/active_record/connection_adapters/abstract/connection_pool.rb:923:in `checkout_new_connection'
activerecord (6.0.0.rc2) lib/active_record/connection_adapters/abstract/connection_pool.rb:902:in `try_to_checkout_new_connection'
activerecord (6.0.0.rc2) lib/active_record/connection_adapters/abstract/connection_pool.rb:863:in `acquire_connection'
activerecord (6.0.0.rc2) lib/active_record/connection_adapters/abstract/connection_pool.rb:587:in `checkout'
activerecord (6.0.0.rc2) lib/active_record/connection_adapters/abstract/connection_pool.rb:431:in `connection'
activerecord (6.0.0.rc2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1106:in `retrieve_connection'
activerecord (6.0.0.rc2) lib/active_record/connection_handling.rb:231:in `retrieve_connection'
activerecord (6.0.0.rc2) lib/active_record/connection_handling.rb:199:in `connection'
activerecord (6.0.0.rc2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.0.rc2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.0.rc2) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.0.rc2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.0.rc2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.0.rc2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.0.rc2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.0.rc2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.0.rc2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
railties (6.0.0.rc2) lib/rails/engine.rb:526:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
  [1m[35m (426.0ms)[0m  [1m[35mCREATE DATABASE "spotify_app_api_development" ENCODING = 'unicode'[0m
  [1m[35m (342.4ms)[0m  [1m[35mCREATE DATABASE "spotify_app_api_test" ENCODING = 'unicode'[0m
DEPRECATION WARNING: warning: white_list_sanitizer isdeprecated, please use safe_list_sanitizer instead. (called from block in <module:ContentHelper> at /Users/victormrecabarren/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/actiontext-6.0.0.rc2/app/helpers/action_text/content_helper.rb:7)
Started GET "/" for ::1 at 2019-08-07 20:42:11 -0400
Processing by Rails::WelcomeController#index as HTML
  Rendering /Users/victormrecabarren/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-6.0.0.rc2/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /Users/victormrecabarren/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-6.0.0.rc2/lib/rails/templates/rails/welcome/index.html.erb (Duration: 9.1ms | Allocations: 485)
Completed 200 OK in 23ms (Views: 14.1ms | ActiveRecord: 0.0ms | Allocations: 2645)


Started GET "/favicon.ico" for ::1 at 2019-08-07 20:42:12 -0400
  
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.0.rc2) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.0.rc2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.0.rc2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.0.rc2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.0.rc2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.0.rc2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.0.rc2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
railties (6.0.0.rc2) lib/rails/engine.rb:526:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
